In [10]:
#basic example

import numpy as np

list1 = [11,22,33]
a =np.array(list1)
print(a)

[11 22 33]


In [11]:
#creating numpy array

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
#creating two dimensional array

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print (arr)

[[1 2 3]
 [4 5 6]]


In [13]:
#creating zero, one, two and three dimensional arrays

import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([  [ [1,2,3],[4,5,6] ],  [ [1,2,3],[4,5,6] ]  ])

print (a.ndim)
print (b.ndim)
print (c.ndim)
print (d.ndim)

0
1
2
3


In [16]:
#accessing array elements with index value

import numpy as np

arr = np.array([1,2,3,4])

print(arr[0]+arr[2])

print (arr[1]*arr[3])


4
8


In [18]:
#accessing two dimensional array elements with index value

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('2nd elemrnt on 1st row:',arr[0,1])

print(arr[1,4]+arr[0,1])

2nd elemrnt on 1st row: 2
12


In [22]:
#accessing three dimensional array elements with index value

import numpy as np

arr = np.array([  [ [1,2,3],[4,5,6] ],  [ [1,2,3],[4,5,6] ]  ])

print (arr[0,0,0]+arr[0,1,0]+arr[1,0,2]+arr[1,1,1])

print (arr[1,0,0]*arr[1,1,0])


13
4
